### ISSUE TITLE
Spotify security

### ISSUE THREAD

**Issue by guidobouman** [kriskuiper/real-time-web-1920#13]
Nice that you're using JWT tokens. If I read your DLC diagram & code correctly, you store the JWT key in the env variables and everything else encrypted, right?

Two questions:
- Are you sending the Spotify tokens to all of the clients? (even if it's encrypted)
- Is it not easier to give each client a UUID, and let the server do the talking to Spotify?

**Comment by kriskuiper** [comment]
Everything is indeed stored encrypted. The `JWT_SECRET`, the key to encrypt and decrypt the tokens so to say is stored in an env variable.

To answer your two questions:
- I am sending the encrypted tokens to all of the clients, this is because the API needs to add a song to the queue of the host so therefore we need the token of the host to do the requests. However (see answer to second question)
- Yeah, that would in fact be easier. What I'm currently thinking is to store the access token in the DB on party creation, as follows:

1. Host creates a party, his / her access token gets encrypted and stored in the DB
2. The party id (from the request params) also gets encrypted and stored in the DB
3. A Party now looks a bit like this:
```js
const myParty = {
  id: 'a', // JWT representing the party ID,
  accessToken: 'b' // JWT representing the accessToken
}
```
4. Host gets a UUID which is stored inside a `users` array in the `Party` and in a `party_uuid` cookie in the client
5. On `disconnect` the cookie gets deleted

Now whenever the socket fires an `add to queue` event, the `song id` and `uuid` are sent to the server. The server checks if there's a user with that id in the party, if so, the server uses the party's accessToken and the `song id` to add the song to the queue. Otherwise the user should get some kind of `not allowed` error or something.

**Comment by guidobouman** [comment]
I think that's a great improvement, and feels like a solid setup!

**Comment by kriskuiper** [comment]
Is implemented some while ago, going to close this.
